name: Build and publish

on:
  push:
    tags:
      - v\d+\.\d+\.\d+
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    # TODO: PyGame doesn't support 3.11 yet
    #        - "3.11"

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - run: poetry --version

      - run: poetry install

      - run: poetry version
    
