---
name: Lint on Pull Request
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    # TODO: PyGame doesn't support 3.11 yet
    #        - "3.11"

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: pipx install poetry

      - run: poetry self add "poetry-dynamic-versioning[plugin]"

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - run: poetry --version

      - run: poetry install

      # TODO: lint changed files and their deps only
      - name: Run Lint
        run: poetry run pre-commit run --all-files
